### ISSUE TITLE
"online" parameter not recognized when creating featuregroup using pyspark

### ISSUE THREAD

**Issue by vinayhudli** [logicalclocks/hops-examples#118]
I get the following error when I try to create online feature store :

create_featuregroup() got an unexpected keyword argument 'online'
Traceback (most recent call last):
TypeError: create_featuregroup() got an unexpected keyword argument 'online'

I'm using hopsworks-0-10-0.tar.gz GCP image.

Thanks,
Vinay

**Comment by jimdowling** [comment]
Hi Vinay. The online feature store is not supported in that version of Hopsworks. We only support it currently in the enterprise version of Hopsworks.

**Comment by vinayhudli** [comment]
@jimdowling any link to download and try out the enterprise edition ? Sorry couldn't find out in the hopsworks docs

**Comment by jimdowling** [comment]
Send us an email at sales- at - logicalclocks.com



Skickat från min Samsung Galaxy-smartphone.



-------- Originalmeddelande --------
Från: vinayhudli <notifications@github.com>
Datum: 2020-01-28 23:41 (GMT+01:00)
Till: logicalclocks/hops-examples <hops-examples@noreply.github.com>
Kopia: Jim Dowling <jim.dowling@ri.se>, Mention <mention@noreply.github.com>
Ämne: Re: [logicalclocks/hops-examples] "online" parameter not recognized when creating featuregroup using pyspark (#118)


@jimdowling<https://github.com/jimdowling> any link to download and try out the enterprise edition ? Sorry couldn't find out in the hopsworks docs
